#!/usr/bin/env python3
"""androidWTF engine.

Reads catalog/bundles/*.yaml and profiles/*.yaml, resolves a profile against the
device's capability tier, and emits or runs the install steps.

There is no YAML dependency. The catalogue is machine-generated by
scripts/gen_bundles.py, so the file shape is a known, restricted subset — block
mappings, block sequences, inline flow maps and folded scalars — and a small
reader for exactly that subset is cheaper and more honest than making every user
build PyYAML on a phone. It refuses anything it does not understand rather than
guessing.
"""

import os
import re
import shutil
import textwrap
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
BUNDLES = ROOT / "catalog" / "bundles"
PROFILES = ROOT / "profiles"
VERSION = "0.1.0-dev"

# Phone terminals are narrow — 40 to 55 columns is normal, against the 80 a
# desktop layout assumes — and SGR 2 (faint) renders as barely-visible grey on
# most of them. So: no faint, and every layout is computed from the real width.
BOLD, GREY, GREEN, YELLOW, RED, CYAN, RESET = (
    "\033[1m", "\033[90m", "\033[32m", "\033[33m", "\033[31m", "\033[36m", "\033[0m")
if not sys.stdout.isatty() or os.environ.get("NO_COLOR"):
    BOLD = GREY = GREEN = YELLOW = RED = CYAN = RESET = ""

DIM = GREY  # kept as an alias so existing call sites stay readable

def width():
    try:
        return max(32, min(100, shutil.get_terminal_size(fallback=(50, 24)).columns))
    except Exception:                                       # noqa: BLE001
        return 50

TIER_COLOUR = {0: GREEN, 1: CYAN, 2: YELLOW, 3: RED}


def step(msg): print(f"{BOLD}{msg}{RESET}")
def warn(msg): print(f"{YELLOW}{msg}{RESET}")
def dim(msg):  print(f"{GREY}{msg}{RESET}")
def rule(w=None): print(f"{GREY}{'─' * (w or width())}{RESET}")


def para(text, indent=0, colour=GREY):
    """Wrap a paragraph to the terminal, so descriptions stop wrapping raggedly."""
    for line in textwrap.wrap(text, max(20, width() - indent)) or [""]:
        print(f"{' ' * indent}{colour}{line}{RESET}")


def ellipsis(s, n):
    return s if len(s) <= n else s[: max(1, n - 1)] + "\u2026"


# ------------------------------------------------------------------ yaml-lite

def _scalar(v):
    v = v.strip()
    if v.startswith("[") and v.endswith("]"):
        inner = v[1:-1].strip()
        return [_scalar(x) for x in inner.split(",")] if inner else []
    if v.startswith("{") and v.endswith("}"):
        out = {}
        for part in _split_commas(v[1:-1]):
            if not part.strip():
                continue
            k, _, val = part.partition(":")
            out[k.strip()] = _scalar(val)
        return out
    if len(v) >= 2 and v[0] == v[-1] == "'":
        return v[1:-1].replace("''", "'")
    if len(v) >= 2 and v[0] == v[-1] == '"':
        return v[1:-1]
    if re.fullmatch(r"-?\d+", v):
        return int(v)
    if v in ("true", "yes", "on"):
        return True
    if v in ("false", "no", "off"):
        return False
    return v


def _bare_colon(s):
    """True if s has a `key: value` colon outside quotes and brackets. Used to
    tell a mapping item (`- id: foo`) from a plain scalar item (`- core`)."""
    depth, quote = 0, None
    for i, ch in enumerate(s):
        if quote:
            if ch == quote:
                quote = None
            continue
        if ch in "'\"":
            quote = ch
        elif ch in "[{":
            depth += 1
        elif ch in "]}":
            depth -= 1
        elif ch == ":" and depth == 0 and (i + 1 == len(s) or s[i + 1] in " \t"):
            return True
    return False


def _split_commas(s):
    """Split on commas that are not inside brackets or quotes."""
    out, depth, quote, cur = [], 0, None, ""
    for ch in s:
        if quote:
            cur += ch
            if ch == quote:
                quote = None
            continue
        if ch in "'\"":
            quote = ch; cur += ch; continue
        if ch in "[{":
            depth += 1
        elif ch in "]}":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur); cur = ""
        else:
            cur += ch
    out.append(cur)
    return out


def load_yaml(path):
    """Parse the restricted subset produced by scripts/gen_bundles.py."""
    lines = []
    for raw in path.read_text().splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        lines.append(raw)

    root, stack, i = {}, [(-1, {})], 0
    stack[0] = (-1, root)

    def container(indent):
        while len(stack) > 1 and stack[-1][0] >= indent:
            stack.pop()
        return stack[-1][1]

    while i < len(lines):
        line = lines[i]
        indent = len(line) - len(line.lstrip())
        body = line.strip()

        if body.startswith("- "):
            item = body[2:].strip()
            parent = container(indent)
            key = parent.pop("__pending__", None) if isinstance(parent, dict) else None
            seq = parent if isinstance(parent, list) else parent.setdefault(key, []) if key else None
            if seq is None:
                seq = parent.setdefault("__seq__", [])
            if item.startswith("{") or item.startswith("["):
                seq.append(_scalar(item)); i += 1; continue
            if not _bare_colon(item):
                # a plain scalar item, e.g. the bundle names in a profile
                seq.append(_scalar(item)); i += 1; continue
            # a mapping that starts on the dash line
            obj = {}
            k, _, v = item.partition(":")
            obj[k.strip()] = _scalar(v) if v.strip() else None
            seq.append(obj)
            stack.append((indent, obj))
            i += 1
            continue

        k, _, v = body.partition(":")
        k, v = k.strip(), v.strip()
        parent = container(indent)
        if v == ">":                                   # folded scalar
            i += 1
            buf = []
            while i < len(lines) and (len(lines[i]) - len(lines[i].lstrip())) > indent:
                buf.append(lines[i].strip()); i += 1
            parent[k] = " ".join(buf)
            continue
        if v == "":                                    # nested block follows
            nxt = lines[i + 1] if i + 1 < len(lines) else ""
            if nxt.strip().startswith("- "):
                parent[k] = []
                stack.append((indent, parent[k]))
            else:
                parent[k] = {}
                stack.append((indent, parent[k]))
            i += 1
            continue
        parent[k] = _scalar(v)
        i += 1

    return root


# -------------------------------------------------------------------- probe

def device_tier():
    """Ask preflight.sh for the tier. Returns (tier, source)."""
    pre = HERE / "preflight.sh"
    if not pre.exists():
        return None, "preflight.sh missing"
    try:
        out = subprocess.run(
            ["bash", "-c", f'source "{pre}"; probe; echo "$WTF_SDK:$WTF_TIER"'],
            capture_output=True, text=True, timeout=30)
        line = out.stdout.strip().splitlines()[-1] if out.stdout.strip() else ""
        sdk, _, tier = line.partition(":")
        # No SDK means getprop was unreadable, which means this is not Android.
        # Reporting Tier 0 there would be a confident wrong answer.
        if not sdk.strip():
            return None, "not an Android device"
        return (int(tier), "probe") if tier.isdigit() else (None, "probe failed")
    except Exception as e:                              # noqa: BLE001
        return None, f"probe error: {e}"


# ----------------------------------------------------------------- catalogue

def load_bundles():
    if not BUNDLES.is_dir():
        sys.exit(f"no catalogue at {BUNDLES}")
    out = {}
    for f in sorted(BUNDLES.glob("*.yaml")):
        d = load_yaml(f)
        out[d["bundle"]] = d
    return out


def load_profile(name):
    for cand in (name, f"android-{name}"):
        p = PROFILES / f"{cand}.yaml"
        if p.exists():
            return load_yaml(p)
    avail = ", ".join(sorted(f.stem for f in PROFILES.glob("*.yaml")))
    sys.exit(f"unknown profile {name!r}. Available: {avail}")


def resolve(profile, bundles, tier=None):
    """Tools a profile installs, filtered to what the device can actually run."""
    limit = profile["requires_tier"] if tier is None else tier
    picked, skipped = [], []
    for b in profile["bundles"]:
        if b not in bundles:
            sys.exit(f"profile {profile['profile']} references missing bundle {b!r}")
        for t in bundles[b]["tools"]:
            (picked if t["tier"] <= limit else skipped).append((b, t))
    return picked, skipped


# ------------------------------------------------------------------ commands

def cmd_list(args):
    profile = load_profile(need(args, "--profile"))
    bundles = load_bundles()
    tier, _ = device_tier()
    limit = tier if tier is not None else profile["requires_tier"]
    picked, skipped = resolve(profile, bundles, limit)

    W = width()
    step(f"{profile['profile']}")
    print(f"{GREY}{len(picked)} tools · Tier {limit}{RESET}")
    print()
    para(profile["description"])
    print()

    # Name column is whatever is left after the tier badge and the provider.
    pw = min(max((len(t["install"][0]["provider"]) for _, t in picked), default=8), 10)
    nw = max(12, W - 8 - pw - 2)
    any_essential = any("essential" in (t.get("flags") or []) for _, t in picked)

    cur = None
    for b, t in picked:
        if b != cur:
            if cur is not None:
                print()
            cur = b
            print(f"  {BOLD}{b}{RESET}")
        c = TIER_COLOUR[t["tier"]]
        star = f"{GREEN}*{RESET}" if "essential" in (t.get("flags") or []) else " "
        name = ellipsis(t["name"], nw)
        prov = ellipsis(t["install"][0]["provider"], pw)
        print(f"  {c}T{t['tier']}{RESET} {star}{name:<{nw}} {GREY}{prov}{RESET}")
    if any_essential:
        print()
        print(f"  {GREEN}*{RESET} {GREY}essential{RESET}")
    if skipped:
        print()
        para(f"{len(skipped)} tools need a higher tier than this device reports "
             f"and were left out.", colour=YELLOW)


def cmd_catalogue(args):
    bundles = load_bundles()
    only = opt(args, "--bundle")
    W = width()
    for name, b in bundles.items():
        if only and name != only:
            continue
        rule(W)
        step(f"{name}")
        print(f"{GREY}{len(b['tools'])} tools{RESET}")
        print()
        para(b["description"])
        print()
        for t in b["tools"]:
            c = TIER_COLOUR[t["tier"]]
            print(f"  {c}T{t['tier']}{RESET} {BOLD}{t['id']}{RESET}")
            para(t["desc"], indent=5)
        print()


def cmd_install(args):
    profile = load_profile(need(args, "--profile"))
    dry = "--dry-run" in args
    bundles = load_bundles()
    tier, src = device_tier()
    if tier is None:
        warn(f"Could not determine the device tier ({src}).")
        if not dry:
            sys.exit("Refusing to install blind. Run 'wtf doctor', or pass --dry-run.")
        tier = profile["requires_tier"]

    if tier < profile["requires_tier"]:
        warn(f"Profile {profile['profile']} wants Tier {profile['requires_tier']}, "
             f"device is Tier {tier}.")
        dim("Installing the subset this device can actually run.")

    picked, skipped = resolve(profile, bundles, tier)
    plan = build_plan(picked)

    W = width()
    step(f"{profile['profile']}")
    print(f"{GREY}Tier {tier} · {len(picked)} tools · {len(plan)} steps{RESET}")
    print()
    for n, (kind, cmd, who) in enumerate(plan, 1):
        label = f"{CYAN}{kind}{RESET}"
        note = f"  {GREY}{who}{RESET}" if who else ""
        print(f"  {GREY}{n:>2}{RESET} {label}{note}")
        # Printed raw, never textwrap'd. The terminal soft-wraps long commands
        # without inserting newlines, so they stay copy-pasteable; textwrap would
        # break a URL across two real lines and silently corrupt it.
        print(f"     {cmd}")
        print()
    if skipped:
        print()
        dim(f"{len(skipped)} tools left out: they need a tier above {tier}.")

    manual = [(b, t) for b, t in picked
              if t["install"][0]["provider"] in ("play", "nethunter", "androidwtf", "web", "builtin")]
    if manual:
        print()
        step(f"{len(manual)} cannot be scripted")
        dim("Play Store, NetHunter Store, first-party apps and documented workflows.")
        dim("Run 'wtf list' for the full set, or use the site's Manual tab.")

    if dry:
        print()
        dim("--dry-run: nothing was executed.")
        return

    print()
    warn("Running the shell steps now. Ctrl-C to stop.")
    env = dict(os.environ)
    env.setdefault("WTF_SRC", str(Path.home() / "wtf" / "src"))
    Path(env["WTF_SRC"]).mkdir(parents=True, exist_ok=True)
    failed = []
    for kind, cmd, who in plan:
        if kind not in ("pkg", "pip", "go", "git", "sh"):
            continue
        step(cmd)
        if subprocess.call(cmd, shell=True, env=env) != 0:
            warn(f"step failed: {who or cmd}")
            failed.append(who or cmd)
    print()
    if failed:
        warn(f"{len(failed)} steps failed:")
        for f in failed:
            dim(f"    {f}")
    else:
        print(f"{BOLD}{GREEN}\u2713 all steps completed{RESET}")


def build_plan(picked):
    """Group the shell-installable steps; report the rest as manual."""
    pkgs, repos, others = [], set(), []
    for _, t in picked:
        s = t["install"][0]
        p = s["provider"]
        if p == "pkg":
            pkgs.extend(str(s["id"]).split())
            if s.get("repo"):
                repos.add(s["repo"])
        elif p == "pip":
            others.append(("pip", f"pip install {s['id']}", t["name"]))
        elif p == "go":
            others.append(("go", f"go install {s['id']}@latest", t["name"]))
        elif p == "git":
            name = str(s["id"]).rstrip("/").rsplit("/", 1)[-1].removesuffix(".git")
            dest = f"$WTF_SRC/{name}"
            others.append(("git",
                           f"git clone --depth 1 {s['id']} {dest} 2>/dev/null || "
                           f"git -C {dest} pull --ff-only",
                           t["name"]))

    plan = []
    if any(k == "git" for k, _, _ in others):
        plan.append(("sh", 'mkdir -p "$WTF_SRC"', "clones land in ~/wtf/src"))
    for r in sorted(repos):
        plan.append(("pkg", f"pkg install -y {r}-repo", f"{r} repo, required below"))
    if pkgs:
        plan.append(("pkg", "pkg update -y", ""))
        plan.append(("pkg", "pkg install -y " + " ".join(sorted(set(pkgs))), ""))
    if any(k == "pip" for k, _, _ in others):
        plan.append(("pkg", "pkg install -y python", "toolchain for the pip steps"))
    if any(k == "go" for k, _, _ in others):
        plan.append(("pkg", "pkg install -y golang", "toolchain for the go steps"))
    if any(k == "git" for k, _, _ in others):
        plan.append(("pkg", "pkg install -y git", "toolchain for the clone steps"))
    plan.extend(others)
    return plan


def cmd_version(_):
    t, src = device_tier()
    c = TIER_COLOUR.get(t, YELLOW)
    print(f"{BOLD}androidWTF{RESET} {VERSION}")
    print(f"{GREY}tier{RESET}       {c}{t if t is not None else '?'}{RESET} {GREY}({src}){RESET}")
    print(f"{GREY}catalogue{RESET}  {ROOT}")
    print(f"{GREY}width{RESET}      {width()} cols")


def cmd_help(_):
    profiles = "\n".join(f"  - {f.stem}" for f in sorted(PROFILES.glob("*.yaml")))
    print(f"""androidWTF {VERSION}

Usage:
  wtf doctor                                Probe this device and report its tier
  wtf list      --profile <name>            Show what a profile would install
  wtf install   --profile <name> [--dry-run]
  wtf catalogue [--bundle <name>]           Dump the tool catalogue
  wtf version
  wtf help

Profiles:
{profiles}

Nothing is installed until an explicit `install`. `doctor`, `list`, `catalogue`
and `--dry-run` change nothing and need no privileges.""")


def opt(args, flag):
    return args[args.index(flag) + 1] if flag in args and args.index(flag) + 1 < len(args) else None


def need(args, flag):
    v = opt(args, flag)
    if not v:
        sys.exit(f"{flag} is required")
    return v


def main():
    argv = sys.argv[1:]
    cmd = argv[0] if argv else "help"
    table = {"list": cmd_list, "install": cmd_install, "catalogue": cmd_catalogue,
             "version": cmd_version, "help": cmd_help}
    if cmd not in table:
        warn(f"unknown command: {cmd}")
        cmd_help(argv)
        sys.exit(1)
    table[cmd](argv[1:])


if __name__ == "__main__":
    main()
